import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 844 } });
await p.goto('http://127.0.0.1:3000/login', { waitUntil: 'networkidle' });
await p.fill('input[type="email"]', 'sld.demo.0002@local.test');
await p.fill('input[type="password"]', 'DemoLocal2026!');
await p.click('button[type="submit"]');
await p.waitForTimeout(3000);
await p.goto('http://127.0.0.1:3000/negocios?q=facturas', { waitUntil: 'networkidle' });
await p.waitForTimeout(2500);
const t = await p.locator('body').innerText();
console.log('incluye El Horno:', t.includes('El Horno'));
console.log('incluye Café:', t.includes('Café'));
const cards = await p.locator('a[href^="/negocio/"]').count();
console.log('cards de negocio en DOM:', cards);
console.log(t.slice(600, 1100));
await b.close();
