"use client";
import {useMemo,useState} from "react";
import Hero from "@/components/home/hero";import Categories from "@/components/home/categories";import Featured from "@/components/home/featured";import {CATEGORIES} from "@/lib/data";
export default function Home({initial}:{initial:any[]}){const[q,setQ]=useState("");const[cat,setCat]=useState<string|null>(null);const list=useMemo(()=>{const t=q.trim().toLowerCase();return initial.filter((b:any)=>{const okCat=!cat||b.category===cat;const hay=[b.name,b.category,b.description,...(b.tags||[]),...(b.items||[]).map((i:any)=>i.name)].join(" ").toLowerCase();return okCat&&(!t||hay.includes(t))})},[q,cat]);const searching=!!q.trim()||!!cat;const catName=CATEGORIES.find(c=>c.id===cat)?.name;
return <main><Hero onSearch={v=>{setQ(v);setCat(null)}}/><Categories active={cat} onSelect={id=>{setCat(id);setQ("")}}/><Featured list={list} title={searching?`Resultados${catName?` · ${catName}`:""}${q?` · “${q}”`:""}`:"Negocios destacados"}/>
<section className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="sld-card overflow-hidden rounded-3xl p-7 sm:p-10"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">🔥 Lo que está pasando</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl" style={{fontFamily:"var(--font-space)"}}>Promos, novedades y oportunidades locales.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-[var(--muted)]">La plataforma está pensada para que el comercio local tenga presencia digital real y para que vos encuentres opciones cerca sin perder tiempo.</p><div className="mt-7 flex flex-wrap gap-3"><a href="/negocios" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-black">Explorar negocios</a><a href="/mapa" className="rounded-xl border border-white/10 px-5 py-3 text-sm font-semibold hover:bg-white/[.04]">Ver mapa</a></div></div></div><div className="sld-card rounded-3xl p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">📍 Cerca tuyo</p><h3 className="mt-2 text-2xl font-bold" style={{fontFamily:"var(--font-space)"}}>Todo conectado al mapa.</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Ubicaciones, cómo llegar y negocios de tu zona en una experiencia simple.</p><a href="/mapa" className="mt-6 inline-flex rounded-xl border border-white/10 px-4 py-2.5 text-sm font-semibold hover:border-cyan-300/30">Abrir mapa →</a></div></div></section>
<section id="como" className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--accent2)]">Simple</p><h2 className="mt-2 text-3xl font-bold" style={{fontFamily:"var(--font-space)"}}>Encontrar. Comparar. Contactar.</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{[["01","Buscás","Escribís qué necesitás y filtrás por categoría."],["02","Descubrís","Mirás perfiles, horarios, productos, ubicación y reseñas."],["03","Contactás","WhatsApp, Instagram, llamada o cómo llegar, directo."]].map(([n,t,d])=><div key={n} className="sld-card rounded-2xl p-6"><span className="text-xs font-black text-violet-300">{n}</span><h3 className="mt-8 text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{d}</p></div>)}</div></section>
<section id="sumate" className="mx-auto max-w-7xl px-4 pb-20 sm:px-6"><div className="relative overflow-hidden rounded-3xl border border-violet-400/20 bg-gradient-to-br from-violet-600/20 via-[#12111d] to-cyan-400/10 p-8 sm:p-12"><div className="absolute -right-20 -top-20 h-60 w-60 rounded-full bg-violet-500/20 blur-3xl"/><div className="relative max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Para comercios</p><h2 className="mt-3 text-3xl font-black sm:text-4xl" style={{fontFamily:"var(--font-space)"}}>Tu negocio también merece una presencia digital de verdad.</h2><p className="mt-4 text-sm leading-6 text-[var(--muted)]">Miniweb, catálogo, promociones, ubicación, contacto y estadísticas. Todo en un mismo lugar y sin tener que saber programar.</p><div className="mt-7 flex flex-wrap gap-3"><a href="/dashboard/nuevo" className="rounded-xl bg-white px-5 py-3 text-sm font-bold text-black">Crear mi negocio</a><a href="/para-negocios" className="rounded-xl border border-white/10 px-5 py-3 text-sm font-semibold hover:bg-white/[.04]">Conocer beneficios</a></div></div></div></section>
</main>}
